// Expansion signals — development activity that predicts future demand
// Each signal is a real project with estimated impact

export interface ExpansionSignal {
  id: string;
  type: "subdivision" | "commercial" | "infrastructure" | "employer" | "rezoning" | "permit-surge";
  title: string;
  description: string;
  zip: string;
  submarket: string;
  status: "planned" | "under-construction" | "approved" | "completed";
  estimatedCompletion: string;
  impact: "high" | "medium" | "low";
  details: string;
  jobs?: number;
  units?: number;
  investment?: string; // e.g. "$1.4B"
  source: string;
  date: string; // when this was added/discovered
}

export const EXPANSION_SIGNALS: ExpansionSignal[] = [
  // ===== SUBDIVISIONS / NEW CONSTRUCTION =====
  {
    id: "gen-park-1",
    type: "subdivision",
    title: "Generation Park — 4,000-acre Master Plan",
    description: "Massive mixed-use development creating an entirely new submarket in NE Houston. Includes residential, commercial, retail, and green space.",
    zip: "77044",
    submarket: "Generation Park / Lake Houston",
    status: "under-construction",
    estimatedCompletion: "2030+",
    impact: "high",
    details: "McCord Development's $4B+ master-planned community. Over 4,000 acres with planned 10M+ sqft of commercial space, 4,000+ residential units, and 500+ acres of parks. Already attracting major employers (Hewlett Packard Enterprise HQ relocation).",
    units: 4000,
    investment: "$4B+",
    source: "McCord Development, City of Houston",
    date: "2026-06",
  },
  {
    id: "east-river-1",
    type: "commercial",
    title: "East River — 150-acre Mixed-Use Development",
    description: "Former KBR campus transformed into a 150-acre mixed-use district on the east side. One of the largest private developments in Houston.",
    zip: "77003",
    submarket: "East End / EaDo",
    status: "under-construction",
    estimatedCompletion: "2028",
    impact: "high",
    details: "Midan Group's 150-acre development along Buffalo Bayou. Planned 2,500+ residential units, 500K+ sqft office, 200K sqft retail, hotel, and 20-acre park. Phase 1 (townhomes + retail) underway. Directly adjacent to METRORail lines.",
    units: 2500,
    investment: "$500M+",
    source: "Midan Group, Houston Business Journal",
    date: "2026-06",
  },
  {
    id: "tmc3-1",
    type: "employer",
    title: "TMC3 — $1.5B Biomedical Research Campus",
    description: "A 30-acre collaborative life sciences campus between Texas Medical Center institutions. Will bring 10,000+ high-income jobs to the area.",
    zip: "77004",
    submarket: "Third Ward / Med Center",
    status: "under-construction",
    estimatedCompletion: "2028",
    impact: "high",
    details: "Joint venture between TMC, Baylor College of Medicine, UT Health Houston, Texas A&M Health Science Center, and UH. Will create 10,000+ permanent jobs averaging $80K+ salaries. Adjacent to Ion District innovation hub. Direct impact on 77004 and surrounding ZIPs.",
    jobs: 10000,
    investment: "$1.5B",
    source: "Texas Medical Center, HBJ",
    date: "2026-06",
  },
  {
    id: "port-hou-1",
    type: "infrastructure",
    title: "Port Houston $1.4B Capital Program",
    description: "Massive port expansion including new container terminals, channel deepening, and rail improvements.",
    zip: "77011",
    submarket: "Magnolia Park / East End",
    status: "under-construction",
    estimatedCompletion: "2028",
    impact: "high",
    details: "Port Houston's 10-year capital plan. Includes the new Bayport Container Terminal expansion, Houston Ship Channel widening (Project 11), and intermodal rail capacity increases. Will create 2,000+ construction jobs and 500+ permanent positions. Direct catalyst for east side industrial-to-residential conversion.",
    jobs: 2500,
    investment: "$1.4B",
    source: "Port Houston Authority",
    date: "2026-06",
  },
  {
    id: "nhhip-1",
    type: "infrastructure",
    title: "NHHIP — North Houston Highway Improvement Project",
    description: "Massive I-45 reconstruction from downtown to Beltway 8. Will reshape the north side corridors for decades.",
    zip: "77020",
    submarket: "Denver Harbor / Fifth Ward",
    status: "under-construction",
    estimatedCompletion: "2030",
    impact: "high",
    details: "TxDOT's $7B+ I-45 reconstruction. Widening, rerouting, and modernizing 26 miles of highway. Direct impact on 77020, 77003, 77009, 77026. Will improve commute times to downtown by 20-30%. Historically, highway projects in Houston trigger a 5-7 year appreciation cycle in adjacent neighborhoods.",
    investment: "$7B+",
    source: "TxDOT",
    date: "2026-06",
  },
  {
    id: "sh288-1",
    type: "infrastructure",
    title: "SH 288 Toll Lane Expansion",
    description: "Managed toll lanes connecting Brazoria County to the Medical Center. Complete — now driving demand in south Houston.",
    zip: "77051",
    submarket: "Sunnyside / South Park",
    status: "completed",
    estimatedCompletion: "2024",
    impact: "medium",
    details: "The SH 288 managed lanes are now fully operational, cutting commute times from south Houston to the Medical Center from 45 min to 15 min during peak hours. This has directly opened up Sunnyside, South Park, and surrounding areas to Med Center workers looking for affordable housing. 26d DOM in 77051 is a direct result.",
    source: "TxDOT, Harris County Toll Road Authority",
    date: "2026-06",
  },
  {
    id: "ion-district-1",
    type: "commercial",
    title: "Ion District Innovation Hub",
    description: "Rice University-anchored innovation district in Midtown, creating a tech/startup ecosystem in Third Ward.",
    zip: "77004",
    submarket: "Third Ward / Midtown",
    status: "under-construction",
    estimatedCompletion: "2027",
    impact: "medium",
    details: "Rice University's 16-acre innovation district centered on the former Sears building. Already houses 100+ startups and tech companies. Phase 2 includes 300K+ sqft of additional office/lab space, retail, and a 200-unit apartment building. Creating a 'Silicon Bayou' effect in Third Ward.",
    jobs: 3000,
    investment: "$200M+",
    source: "Rice University, Houston Chronicle",
    date: "2026-06",
  },
  {
    id: "heights-north-1",
    type: "permit-surge",
    title: "Heights North Teardown-Rebuild Wave",
    description: "Sustained permit surge for teardown-rebuilds and townhome construction in the northern Heights.",
    zip: "77009",
    submarket: "Heights North / Near Northside",
    status: "under-construction",
    estimatedCompletion: "Ongoing",
    impact: "medium",
    details: "77009 leads our dataset in total listings (612 active) and new listings (136/mo). The teardown-rebuild wave continues to push north from the Heights core. Townhome developments replacing older single-family homes. 26d DOM proves demand absorbs new supply quickly. Premium pricing ($435K med) limits further upside compared to earlier stages.",
    units: 500,
    source: "City of Houston Building Permit Data",
    date: "2026-06",
  },
  {
    id: "fm2100-1",
    type: "infrastructure",
    title: "FM 2100 Widening (Generation Park)",
    description: "Major road widening project supporting Generation Park development in NE Houston.",
    zip: "77044",
    submarket: "Generation Park / Lake Houston",
    status: "under-construction",
    estimatedCompletion: "2027",
    impact: "medium",
    details: "Harris County's FM 2100 widening from 2 to 6 lanes between Beltway 8 and the Grand Parkway. Directly supports Generation Park's 4,000-acre development. When complete, will reduce commute times to downtown/IAH by 15-20 minutes and unlock additional development parcels.",
    investment: "$150M",
    source: "Harris County Precinct 2, TxDOT",
    date: "2026-06",
  },
  {
    id: "bw8-connector-1",
    type: "infrastructure",
    title: "BW8 / SH 225 Connector",
    description: "Direct freeway connector improving access between Beltway 8 and SH 225 in east Houston.",
    zip: "77012",
    submarket: "Harrisburg",
    status: "under-construction",
    estimatedCompletion: "2026",
    impact: "medium",
    details: "TxDOT's direct connector ramps between Beltway 8 (South) and SH 225. Will significantly improve access to the Port Houston industrial corridor and east side residential areas. Harrisburg (77012) benefits directly — currently the lowest inventory ZIP at 71 total listings, suggesting supply constraint that will be tested by improved access.",
    investment: "$80M",
    source: "TxDOT",
    date: "2026-06",
  },
  {
    id: "spring-branch-1",
    type: "rezoning",
    title: "Spring Branch Townhome Infill",
    description: "Continued upzoning and townhome development in Spring Branch West, driven by Heights spillover.",
    zip: "77043",
    submarket: "Brittmoore / Spring Branch W",
    status: "under-construction",
    estimatedCompletion: "Ongoing",
    impact: "medium",
    details: "Spring Branch has seen significant upzoning from single-family to townhome-permitting over the past 5 years. 77043's 197 active listings and 25d DOM show strong demand. The $450K med price point is still 30-40% below inner-loop (77007, 77008), making it a value play for buyers priced out of the Heights.",
    units: 300,
    source: "City of Houston Planning, HBJ",
    date: "2026-06",
  },
  {
    id: "sunny-side-1",
    type: "permit-surge",
    title: "Sunnyside Revitalization — SH 288 Corridor",
    description: "Redevelopment activity accelerating along the SH 288 corridor in Sunnyside and South Park.",
    zip: "77051",
    submarket: "Sunnyside / South Park",
    status: "under-construction",
    estimatedCompletion: "2028",
    impact: "medium",
    details: "Post-SH 288 completion, Sunnyside has seen accelerating redevelopment activity. New townhome projects, church-to-residential conversions, and commercial infill. 26d DOM at $270K with 8.4% yield is an anomaly — it suggests the market is ahead of the narrative. City of Houston has targeted Sunnyside for infrastructure investment.",
    source: "City of Houston, Greater Houston Partnership",
    date: "2026-06",
  },
  {
    id: "denver-harbor-1",
    type: "permitsurge",
    title: "Denver Harbor — NHHIP Impact Zone",
    description: "Permit activity accelerating from a very low base as NHHIP construction drives interest.",
    zip: "77020",
    submarket: "Denver Harbor / Fifth Ward",
    status: "under-construction",
    estimatedCompletion: "2028",
    impact: "medium",
    details: "77020 has the #1 overall growth score in our model. 27d DOM with 9.4% yield and NHHIP as catalyst. Permit activity is up 40% YoY (from a low base). The combination of fast sell-through, high yield, and infrastructure catalyst is unique in Houston. The NHHIP project will directly improve access to downtown and the north side.",
    source: "City of Houston Building Permits, TxDOT",
    date: "2026-06",
  },
  {
    id: "kashmere-1",
    type: "infrastructure",
    title: "Northeast Corridor Investment",
    description: "City and county infrastructure investments in the Kashmere Gardens / Northeast corridor.",
    zip: "77026",
    submarket: "Kashmere Gardens",
    status: "planned",
    estimatedCompletion: "2029",
    impact: "low",
    details: "Harris County and City of Houston have announced targeted infrastructure investments in the Northeast corridor, including street improvements, drainage, and a new community center. However, no major private development commitments yet. 77026 has the lowest entry price ($168K) but 79d DOM indicates investors are still waiting for concrete catalysts.",
    source: "Harris County Precinct 1, City of Houston",
    date: "2026-06",
  },
  {
    id: "south-houston-1",
    type: "employer",
    title: "Houston Medical Center Employment Growth",
    description: "TMC employment continues to grow, driving demand in the SH 288 corridor south of the Med Center.",
    zip: "77033",
    submarket: "South Houston",
    status: "under-construction",
    estimatedCompletion: "Ongoing",
    impact: "medium",
    details: "The Texas Medical Center adds 3,000-5,000 new jobs annually. As the Med Center expands south toward SH 288, affordable bedroom communities along the corridor (77033, 77051) benefit. 77033's 11.5% gross yield is the highest in our dataset — the market hasn't fully priced in the Med Center expansion yet.",
    jobs: 3000,
    source: "Texas Medical Center, Greater Houston Partnership",
    date: "2026-06",
  },
  {
    id: "addicks-1",
    type: "infrastructure",
    title: "Addicks Reservoir Flood Mitigation",
    description: "Post-Harvey flood control improvements in the Addicks Reservoir area affecting 77040/77041.",
    zip: "77041",
    submarket: "Carverdale / NW Houston",
    status: "under-construction",
    estimatedCompletion: "2027",
    impact: "medium",
    details: "Army Corps of Engineers post-Harvey improvements to Addicks Dam and reservoir. Includes outlet structure modifications and downstream channel improvements. When complete, these projects could unlock development in currently flood-prone portions of 77040/77041. Combined with the area's #1 appreciation ranking and 23d DOM, this could remove the main headwind.",
    investment: "$500M+",
    source: "US Army Corps of Engineers, Harris County Flood Control",
    date: "2026-06",
  },
];
